### ISSUE TITLE
Comments on your reflections

### ISSUE THREAD

**Issue by jennybc** [dchiu911/naim#1]
> Trying to figure out how to get an overview.md to be produced from the vignette YAML

I recently had the some problem. I found that this YAML, coupled with the new-ish vignette roclet for devtools, causes the intermediate Markdown of my vignette to be produced whenever I document my package:

``` r

---
title: "googlesheets Basic Usage"
author: "Joanna Zhao, Jenny Bryan"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    keep_md: true
vignette: >
  %\VignetteIndexEntry{googlesheets Basic Usage}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}

---
```

> My question is whether this workflow would coincide with CRAN guidelines after my modification to the .Rbuildignore file.

Yes I think you're fine on this point. If you've got stuff in .Rbuildignore, it won't make it to CRAN.

> There seems to be a lot of repeated information in my documentation

This is good for the user, though presents obvious pitfalls for not contradicting yourself as you edit things.

**Comment by dchiu911** [comment]
Thanks for sharing this YAML! It'll definitely lubricate the package building process more.

I suppose the documentation felt repetitive because I only had two functions. With a more comprehensive package I'd likely find myself emphasizing different things in different places.
